---
title: "prediction"
date: "May 3, 2017"
output: html_document
---
```{r packages}
library(dplyr)
library(corrplot)
library(forcats)
library(randomForest)
library(gbm)
```

```{r load data}
load("ames_train.Rdata")
load("ames_test.Rdata")
load("ames_validation.Rdata")
load("predict.Rdata")
```

```{r}
train = ames_train %>% 
  mutate(datset = "train")
test = ames_test %>%
  mutate(datset = "test")
valid = ames_validation %>%
  mutate(datset = "valid")

dat = train %>% 
  rbind(., test) %>%
  rbind(., valid)

findNA = function(col){
  numNA = sum(is.na(col) | col == "")
  type = class(col)
  level = paste(as.character(levels(col)), collapse = ";")
  large_0 = sum(table(col) > 0)
  return(c(numNA, type, level, large_0))
}

train_info = lapply(dat, findNA)
train_info = as.data.frame(do.call(rbind, train_info), stringsAsFactors = F)
colnames(train_info) = c("numNA", "class", "level")
train_info$numNA = as.numeric(train_info$numNA)
train_info$missing_ratio = train_info$numNA/nrow(ames_train)
train_info$names = rownames(train_info)

features_drop = rownames(train_info)[train_info$missing_ratio > 0.5]
features_remain = rownames(train_info)[train_info$missing_ratio <= 0.5]

dat1 = dat[, c(features_remain)]

# Bsmt.Exposure
dat1$Bsmt.Exposure[dat1$Bsmt.Exposure == "" &
                     !is.na(dat1$Bsmt.Exposure)] = names(sort(table(dat1$Bsmt.Exposure), 
                                                              decreasing = T))[1]
dat1$Mas.Vnr.Type[dat1$Mas.Vnr.Type == ""] = "None"
dat1$Electrical[dat1$Electrical == ""] = names(sort(table(dat1$Electrical),
                                                    decreasing = T))[1]
dat1$BsmtFin.Type.2[dat1$BsmtFin.Type.2 == "" &
                      !is.na(dat1$BsmtFin.Type.2)] = NA

dat2 = dat1 %>%
  dplyr::select(-Garage.Yr.Blt) %>%
  filter(PID != 903426160) %>%
  mutate(MS.SubClass = as.factor(MS.SubClass),
         Lot.Frontage = ifelse(is.na(Lot.Frontage), 0, Lot.Frontage),
         #Fireplace.Qu = fct_explicit_na(Fireplace.Qu, "Unknown"),
         #Fireplace.Qu = as.numeric(factor(Fireplace.Qu, 
         #                                  levels = c("Unknown", "Po", "Fa", 
         #                                             "TA", "Gd", "Ex"))),
         Garage.Cond = fct_explicit_na(Garage.Cond, "Unknown"),
         Garage.Cond = as.numeric(factor(Garage.Cond, 
                                         levels = c("Unknown", "Po", "Fa", 
                                                    "TA", "Gd", "Ex"))),
         Garage.Qual = fct_explicit_na(Garage.Qual, "Unknown"),
         Garage.Qual = as.numeric(factor(Garage.Qual, 
                                         levels = c("Unknown", "Po", "Fa", 
                                                    "TA", "Gd", "Ex"))),
         Garage.Type = fct_explicit_na(Garage.Type, "Unknown"),
         Garage.Finish = fct_explicit_na(Garage.Finish, "Unknown"),
         Garage.Finish = as.numeric(factor(Garage.Finish, 
                                           levels = c("Unknown", "Unf", 
                                                      "RFn", "Fin"))),
         Bsmt.Qual = fct_explicit_na(Bsmt.Qual, "Unknown"),
         Bsmt.Qual = as.numeric(factor(Bsmt.Qual, 
                                       levels = c("Unknown", "Po", "Fa", 
                                                  "TA", "Gd", "Ex"))),
         Bsmt.Cond = fct_explicit_na(Bsmt.Cond, "Unknown"),
         Bsmt.Cond = as.numeric(factor(Bsmt.Cond, 
                                       levels = c("Unknown", "Po", "Fa", 
                                                  "TA", "Gd", "Ex"))),
         Bsmt.Exposure = fct_explicit_na(Bsmt.Exposure, "Unknown"),
         Bsmt.Exposure = as.numeric(factor(Bsmt.Exposure, 
                                           levels = c("Unknown", "No", "Mn", 
                                                      "Av", "Gd"))),
         BsmtFin.Type.1 = fct_explicit_na(BsmtFin.Type.1, "Unknown"),
         BsmtFin.Type.1 = as.numeric(factor(BsmtFin.Type.1, 
                                            levels = c("Unknown", "Unf","LwQ",
                                                       "Rec", "BLQ", 
                                                       "ALQ", "GLQ"))),
         BsmtFin.Type.2 = fct_explicit_na(BsmtFin.Type.2, "Unknown"),
         BsmtFin.Type.2 = as.numeric(factor(BsmtFin.Type.2, 
                                            levels = c("Unknown", "Unf","LwQ",
                                                       "Rec", "BLQ", 
                                                       "ALQ", "GLQ"))),
         Mas.Vnr.Area = ifelse(is.na(Mas.Vnr.Area), 0, Mas.Vnr.Area),
         Utilities = as.numeric(factor(Utilities, 
                                       levels = c("ELO","NoSeWa","NoSewr","AllPub"))),
         Lot.Shape = as.numeric(factor(Lot.Shape, 
                                       levels = c("IR3","IR2","IR1","Reg"))),
         Exter.Qual= as.numeric(factor(Exter.Qual, 
                                       levels = c("Po", "Fa", 
                                                  "TA", "Gd", "Ex"))),
         Land.Slope =  as.numeric(factor(Land.Slope, 
                                         levels = c("Sev", "Mod","Gtl"))),
         Exter.Cond = as.numeric(factor(Exter.Cond, 
                                        levels = c("Po", "Fa", 
                                                   "TA", "Gd", "Ex"))),
         Heating.QC = as.numeric(factor(Heating.QC, 
                                        levels = c("Po", "Fa", 
                                                   "TA", "Gd", "Ex"))),
         Electrical = as.numeric(factor(Electrical, 
                                        levels = c("Mix", "FuseP", 
                                                   "FuseF", "FuseA", "SBrkr"))),
         Kitchen.Qual = as.numeric(factor(Kitchen.Qual, 
                                          levels = c("Po", "Fa", 
                                                     "TA", "Gd", "Ex"))),
         Functional = as.numeric(factor(Functional, 
                                        levels = c("Sal", "Sev", 
                                                   "Maj2", "Maj1", "Mod",
                                                   "Min2","Min1","Typ"))),
         Paved.Drive = as.numeric(factor(Paved.Drive, 
                                         levels = c("N", "P","Y"))),
         Bsmt.Half.Bath = ifelse(is.na(Bsmt.Half.Bath), 0, Lot.Frontage),
         Bsmt.Full.Bath = ifelse(is.na(Bsmt.Full.Bath), 0, Lot.Frontage)
  )

dat3 = dat2 %>%
  dplyr::select(-Condition.2)

train_clean = dat3[dat3$datset == "train",] %>%
  dplyr::select(-datset)
test_clean = dat3[dat3$datset == "test",] %>%
  dplyr::select(-datset)
validation_clean = dat3[dat3$datset == "valid",] %>%
  dplyr::select(-datset)
```

```{r}
suppressMessages(library(MASS))
suppressMessages(library(knitr))

set.seed(1)
# colnames(train_clean)[23]   ,"Utilities","Bsmt.Full.Bath")
# delete_list = c(16,74,46,48,39,23,24,25)
delete_list = c(23,24,25,39,44,45,46)

cont_var = setdiff(names(sapply(train_clean[,-delete_list],class))[sapply(train_clean[,-delete_list],class)!="factor"],c("PID","price"))
factor_var = names(sapply(train_clean[,-delete_list],class))[sapply(train_clean[,-delete_list],class)=="factor"]

interac = paste("area",paste(":",factor_var))
fmla = as.formula(paste("log(price) ~ Neighborhood:area+", paste(cont_var, collapse= "+"),"+",paste(factor_var,collapse = "+"),"+",paste(interac,collapse = "+")))


suppressMessages(library(glmnet))

model2 = cv.glmnet(model.matrix(fmla,train_clean)[,-1], 
                      log(train_clean$price), 
                      alpha=1,
                      lambda= 10^seq(4,-3,length= 1000))
model2.lambda.best = model2$lambda.min

tmp_coeffs <- coef(model2, s = "lambda.min")
df = data.frame(name = tmp_coeffs@Dimnames[[1]][tmp_coeffs@i+1], coefficient = tmp_coeffs@x)
# kable(df)


model2.pred = predict(model2, 
                      model.matrix(fmla,test_clean)[,-1],
                      s = model2.lambda.best)


# replace model1 with model2
predictions = data.frame(fit = exp(model2.pred))
predictions$PID = ames_test$PID
```

```{r}
nsim = 50
y_test_pred = matrix(0,nrow(test_clean),nsim)

for(i in 1:nsim){
  model3 = cv.glmnet(model.matrix(fmla,train_clean)[,-1],
                      log(train_clean$price),
                      alpha=1,
                      lambda= 10^seq(4,-3,length= 1000))
  model3.lambda.best = model3$lambda.min


  model3.pred = predict(model3,
                      model.matrix(fmla,test_clean)[,-1],
                      s = model3.lambda.best)
  y_test_pred[,i] = model3.pred
}

y_mean = apply(exp(y_test_pred),1,mean)
y_quantile = apply(exp(y_test_pred),1,quantile,c(0.025,0.975))
#
# coverage(y_quantile[1,],y_quantile[2,],test_clean$price)
# RMSE(y_mean,test_clean$price)
predictions$lwr = y_quantile[1,]
predictions$upr = y_quantile[2,]
colnames(predictions)[1]="fit"
save(predictions, file="predict.Rdata")

```

```{r}
validation_clean$price = 1
model4.pred = predict(model2, 
                      model.matrix(fmla,validation_clean)[,-1],
                      s = model2.lambda.best)
```

```{r}
y_test_pred2 = matrix(0,nrow(validation_clean),nsim)

for(i in 1:nsim){
  model3 = cv.glmnet(model.matrix(fmla,train_clean)[,-1],
                      log(train_clean$price),
                      alpha=1,
                      lambda= 10^seq(4,-3,length= 1000))
  model3.lambda.best = model3$lambda.min


  model3.pred = predict(model3,
                      model.matrix(fmla,validation_clean)[,-1],
                      s = model3.lambda.best)
  y_test_pred2[,i] = model3.pred
}

y_mean2 = apply(exp(y_test_pred2),1,mean)
y_quantile2 = apply(exp(y_test_pred2),1,quantile,c(0.025,0.975))
```

```{r create }
# name dataframe as predictions! DO NOT CHANGE
predictions = data.frame(PID = ames_validation$PID)
predictions$fit = exp(model4.pred)
predictions$lwr = y_quantile2[1,]
predictions$upr = y_quantile2[2,]
save(predictions, file="predict-validation.Rdata")
```
